In [9]:
import numpy as np

In [36]:
preds = np.random.rand(4500, 750, 2)
preds.shape
preds

array([[[0.35885374, 0.62676029],
        [0.11568794, 0.44984548],
        [0.57234804, 0.28903402],
        ...,
        [0.25603351, 0.12748847],
        [0.79083922, 0.55045302],
        [0.66931587, 0.97616602]],

       [[0.50245865, 0.9059413 ],
        [0.75089031, 0.00712365],
        [0.06454603, 0.26245748],
        ...,
        [0.15237727, 0.14036896],
        [0.58190103, 0.60556858],
        [0.76258613, 0.26109438]],

       [[0.25906736, 0.77659851],
        [0.87298313, 0.93604646],
        [0.63546153, 0.84117461],
        ...,
        [0.61938883, 0.70253315],
        [0.30305182, 0.08203173],
        [0.97824743, 0.6776764 ]],

       ...,

       [[0.8689076 , 0.01448215],
        [0.42205637, 0.37021343],
        [0.79529498, 0.06009917],
        ...,
        [0.4665784 , 0.77944252],
        [0.52330511, 0.02311216],
        [0.94925797, 0.89896469]],

       [[0.52091015, 0.80630682],
        [0.90405716, 0.56953621],
        [0.00137729, 0.65768761],
        .

In [46]:
max_pos_idx = np.argmax(preds[:, :, 0], axis=1)
max_prob = np.max(preds[:, :, 0], axis=1)
print(max_pos_idx)
print(max_prob)

[450 711 570 ... 488 464 623]
[0.999861   0.99672609 0.99501634 ... 0.99978538 0.99617845 0.99747574]


In [38]:
preds = np.random.rand(4500, 2)
preds.shape
preds

array([[[0.42981049, 0.82998218],
        [0.90116601, 0.44093598],
        [0.07379107, 0.24809304],
        ...,
        [0.74478253, 0.69042559],
        [0.27485212, 0.09048621],
        [0.32914215, 0.56880283]],

       [[0.96449792, 0.64279589],
        [0.91195274, 0.18290976],
        [0.98417393, 0.4391652 ],
        ...,
        [0.30957372, 0.10341161],
        [0.14042955, 0.52170824],
        [0.36303308, 0.54583813]],

       [[0.42410733, 0.74354715],
        [0.00577305, 0.42324089],
        [0.31216295, 0.32661457],
        ...,
        [0.2251652 , 0.68219845],
        [0.220631  , 0.79554788],
        [0.04250036, 0.35275283]],

       ...,

       [[0.84171779, 0.18027565],
        [0.28820806, 0.65991908],
        [0.64006264, 0.91568361],
        ...,
        [0.48330808, 0.32703548],
        [0.59983648, 0.3507445 ],
        [0.83174949, 0.13942122]],

       [[0.45494919, 0.68690859],
        [0.3507659 , 0.79645734],
        [0.12125524, 0.10384265],
        .

In [39]:
max_pos_idx = np.argmax(preds[:, 0], axis=0)
max_prob = np.max(preds[:, 0], axis=0)
print(max_pos_idx)
print(max_prob)

[2272 1708]
[0.99957686 0.99986886]


In [11]:
import torch
import numpy as np

In [2]:
last_hidden_state = torch.rand(128, 64, 768)

In [58]:
print(last_hidden_state.shape)
print(last_hidden_state.unsqueeze(-1).shape)
print((last_hidden_state.unsqueeze(-1)).sum(1).shape)

torch.Size([128, 64, 768])
torch.Size([128, 64, 768, 1])
torch.Size([128, 768, 1])


In [3]:
print(last_hidden_state.mean(0).shape)

torch.Size([64, 768])


In [8]:
print(last_hidden_state[:, 0, :].shape)

torch.Size([128, 768])


In [9]:
fin =[]

In [14]:
fin = np.vstack(last_hidden_state)
fin.shape

(8192, 768)

In [13]:
fin

array([[0.56471384, 0.7245168 , 0.97719437, ..., 0.3802544 , 0.4924476 ,
        0.12435031],
       [0.14190078, 0.81030136, 0.45024008, ..., 0.49022263, 0.56941247,
        0.39558887],
       [0.9642991 , 0.90416795, 0.08739191, ..., 0.9540883 , 0.24052441,
        0.7847944 ],
       ...,
       [0.5468793 , 0.8832087 , 0.9560511 , ..., 0.20327032, 0.85807145,
        0.1506275 ],
       [0.793249  , 0.97038305, 0.44503224, ..., 0.6106655 , 0.06232744,
        0.46073228],
       [0.81063646, 0.18758464, 0.56721693, ..., 0.7899558 , 0.81977075,
        0.41923803]], dtype=float32)